"""
05.2.1 Random generator.
A simple random generator is obtained by the formula
𝑟new   =  (𝑎  × 𝑟old +  𝑏) % 𝑚

where 𝑎 , 𝑏 , 𝑟 and 𝑚 are integers; moreover, the value rnew is
equal to rold in the following computation. Write a program that
asks the user to enter an initial value for rold. Then print the
first 100 random integers generated by this formula,
using a = 32310901, b = 1729, and m = 224. [P4.27]
"""

def main():

    a = 32310901
    b = 1729
    m = 224

    r = int(input("Bir R değeri giriniz: "))

    for i in range(100):

        rnew = (((a*r)+b)%m)
        print(rnew)
        r = rnew

if __name__ == "__main__":
    main()

